#!/bin/sh

/usr/bin/invoke_app "$@" -C "start_jupyter -T @tool E599_Aging.ipynb" \
                        -t E599_Aging \
                        -u anaconda3-5.1 \
                        -e TOOL_PYTHONPATH=/apps/share64/debian7/anaconda/anaconda3-5.1/tools/tellurium/20190823/lib/python3.6/site-packages
